[project]
name = "nats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "marimo>=0.17.7",
    "nats-py>=2.11.0",
    "ruff>=0.14.4",
    "typer>=0.20.0",
]
